apiVersion: v1
entries:
    webapp:
    - created: 2022-10-06T16:23:20.499543808-06:00
      description: Create a basic nginx HTTP server
      home: https://helm.sh/helm
      name: webapp
      sources:
      - https://github.com/helm/charts
      urls:
      - https://github.com/mohamedanwer006/helm-hol/blob/gh-pages/charts/web-app-0.1.tgz
      version: 1.1.0
generated: "2022-07-24T18:28:25.649860985+02:00"
